In [2]:
import pandas as pd
df = pd.read_csv('iphone.csv')
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [3]:
df.columns = df.columns.str.replace(' ','_')
df.head()

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [22]:
df[df['Star_Rating'].isna()]

Empty DataFrame
Columns: [Product_Name, Product_URL, Brand, Sale_Price, Mrp, Number_Of_Ratings, Number_Of_Reviews, Upc, Star_Rating, Ram]
Index: []

In [16]:
mean_value = df['Star_Rating'].mean()

In [20]:
df['Star_Rating'].fillna(mean_value, inplace = True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_20904\2760079153.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Star_Rating'].fillna(mean_value, inplace = True)

In [21]:
df['Star_Rating'].head()

0    4.600000
1    4.600000
2    4.600000
3    4.576271
4    4.500000
Name: Star_Rating, dtype: float64

In [24]:
df['Discount_Percentage'] = ((df['Mrp'] - df['Sale_Price']) /df['Mrp']) * 100

In [34]:
x = df['Discount_Percentage'].max()
max_discount = df[df['Discount_Percentage'] == x]
max_discount.head()

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram,Discount_Percentage
18,"APPLE iPhone 11 Pro (Midnight Green, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,74999,106600,7088,523,MOBFKCTSN3TG3RFJ,4.6,4 GB,29.644465

In [37]:
df['storage'] = df['Product_Name'].str.extract(r'(\d+)\s?GB')

In [4]:
df.head()

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [9]:
top_5 = df.nlargest(5,'Number_Of_Reviews')[['Product_Name','Number_Of_Reviews']]
top_5

                       Product_Name  Number_Of_Reviews
23  Apple iPhone SE (White, 256 GB)               8161
53  APPLE iPhone SE (Black, 128 GB)               8161
55    APPLE iPhone SE (Red, 128 GB)               8161
57   APPLE iPhone SE (Black, 64 GB)               8161
52   APPLE iPhone SE (White, 64 GB)               8154

In [13]:
hl_df = df['Mrp'].max()-df['Mrp'].min()
print(hl_df)

110000

In [18]:
third_df = df.nlargest(3,'Mrp')[['Product_Name','Mrp']].iloc[-1]
third_df

Product_Name    APPLE iPhone 11 Pro (Space Grey, 512 GB)
Mrp                                               140300
Name: 19, dtype: object

In [22]:
avg_df = df[df['Mrp']>100000]['Mrp'].mean()
avg_df

np.float64(130559.09090909091)

In [30]:
df_128 = df[df['Product_Name'].str.contains('128 GB', case= False, na = False)]
df_128['Rating_To_Review_Ratio'] = (df_128['Number_Of_Ratings'] /	df_128['Number_Of_Reviews'])
max_ratio_product = df_128.sort_values('Rating_To_Review_Ratio', ascending=False).iloc[0]['Product_Name']

max_ratio_product

C:\Users\Administrator\AppData\Local\Temp\ipykernel_15448\2326031746.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_128['Rating_To_Review_Ratio'] = (df_128['Number_Of_Ratings'] /	df_128['Number_Of_Reviews'])

'APPLE iPhone 11 (Black, 128 GB)'